config/routes.rb
Rails.application.routes.draw do
  # the following code that is commented out is not required as we are using resources.
  # resources is part of rub that means we aren't calling get, posts or patch etc
  # # Read all tasks
  # get 'restaurants', to: 'restaurants#index'

  # # Read the details of one restaurant
  # get 'restaurant/:id', to: 'restaurants#show', as: "restaurant"

  #   # create a restaurant 2 REQUESTS
  # get 'restaurants/new', to: 'restaurants#new', as: "new"
  # post 'restaurants', to: "restaurants#create"

  # get 'restaurants/:id/reviews/new', to: 'reviews#new', as: "new_restaurant_review"
  # post 'reviews', to: "reviews#create"

  # this is nested resources. as reviews will be shown on a restaurants' page w/ capabilities of
  # only adding a new review,  we have only 2 optinos: new and create.
  resources :restaurants, only: [:index, :show, :new, :create] do
    resources :reviews, only: [:new, :create]
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/restaurant.rb
# dependent destroy means we destory the reviews if the restaurant is deleted.
class Restaurant < ApplicationRecord
  has_many :reviews, dependent: :destroy
  validates :name, uniqueness: true, presence: true
  validates :address, presence: true
  validates :category, presence: true, inclusion: { in: ["chinese", "italian", "japanese", "french", "belgian"] }
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :restaurant
  validates :content, presence: true
  validates :rating, inclusion: { in: [0, 1, 2, 3, 4, 5] }, numericality: { only_integer: true}
  end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController

  def index
    @restaurants = Restaurant.all
  end

  def show
    @restaurant = Restaurant.find(params[:id])
  end

  def new

    @restaurant = Restaurant.new
  end

  def create
    # restaurant_params are what we pick up from the _form inputs, that are shown on new.html.erb
    @restaurant = Restaurant.new(restaurant_params)
    if @restaurant.save
     redirect_to restaurant_path(@restaurant)
    else
      #if we haven't got a valid save to our db, we will render a new page.
      render :new
    end
  end

  private
# we require the 3 params that are sent from the form , in order to save them to @restaurant in create.
  def restaurant_params
    params.require(:restaurant).permit(:name, :category, :address)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

  def new
    # when creating a new review, we need to know what restaurant it refers to w/ Restaurant.find
    @restaurant = Restaurant.find(params[:restaurant_id])
    @review = Review.new
  end

  def create
    # when creating a new review, we need to know what restaurant it refers to w/ Restaurant.find
    @restaurant = Restaurant.find(params[:restaurant_id])
    # it needs to have the review params we set out in the review_params method below.
    @review = Review.new(review_params)
    @review.restaurant = @restaurant

    if @review.save
     redirect_to restaurant_path(@restaurant)
    else
      # if it deosn't save (such as all params not being sent through, it will render a new form page)
      render :new
    end
  end

  def review_params
    params.require(:review).permit(:content, :rating)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>

  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <title>RailsYelpMvp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/layouts/index.html.erb
<h1>My Restaurants</h1>

<% @restaurants.each do |restaurant| %>
  <%= restaurant.name  %>
<% end %>

app/views/restaurants/_form.html.erb
<%= simple_form_for(@restaurant) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div><%= @restaurant.errors.full_messages %></div>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :address %>
    <%= f.input :category %>
    <%= f.input :phone_number %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/restaurants/index.html.erb
<!--  We link to the restaurant's name and it will take us to that particular restaurant -->
<h1>My Restaurants</h1>

<% @restaurants.each do |restaurant| %>
 <p><%= link_to restaurant.name, restaurant_path(restaurant) %></p>
<% end %>

app/views/restaurants/new.html.erb
<!-- We are rendering from _form to complete this page -->

<h1>New Restaurant</h1>

<%= render 'form', restaurant: @restaurant %>

app/views/restaurants/show.html.erb
<!-- This form takes the restaurant name, then iterates over each review and displays them -->
<!--  The review.content and review.rating are params that we require (see reviews_controller) -->
<h1>My Restaurant </h1>

<p> <%= @restaurant.name %>
<%= link_to "Create review", new_restaurant_review_path(@restaurant) %>
</p>
<% @restaurant.reviews.each do |review| %>
<p><%= review.content %> <%= review.rating %></p>
<% end %>

app/views/reviews/create.html.erb
<!-- Nothing to do here -->

<h1>Reviews#create</h1>
<p>Find me in app/views/reviews/create.html.erb</p>

app/views/reviews/new.html.erb
<!--
Remember we must add each parameter required  as an input for our form.
 -->
<h1>Reviews#new</h1>
<p>Find me in app/views/reviews/new.html.erb</p>
<%= simple_form_for [@restaurant, @review] do |f| %>
  <%= f.input :content %>
  <%= f.input :rating %>
  <%= f.submit "add a review", class: "btn btn-primary" %>
<% end %>